### ISSUE TITLE
Spotifyd install issue

### ISSUE THREAD

**Issue by jheistand** [snorre-k/musicbox#11]
The spotifyd install script had these errors:
sed: -e expression #1, char 44: unterminated `s' command
sed: -e expression #1, char 37: unterminated `s' command
Resulting in the credentials in mopidy.conf not being properly imported into spotifyd.conf.  I manually edited the conf file and everything worked after a reboot.  

I suspect there is a typo in this block of the spotifyd install.sh script, but I am pretty green with linux and bash scripting.  
          SPOT_CFG=`sudo sed '/^\[spotify\]/,/^\[.*\]/!d;//d' /etc/mopidy/mopidy.conf`
          username=`echo "$SPOT_CFG" | grep username | awk -F= '{print $2}' | tr -d ' '`
          password=`echo "$SPOT_CFG" | grep password | awk -F= '{print $2}' | tr -d ' '`

**Comment by snorre-k** [comment]
Thx for the bug report.
The error occurs, when the password has special chars like "/".
Unfortunately I am not aware, how to catch such errors and escape then (with a "\").

As you were able to manually fix your problem, I hope everything works fine now.
