### ISSUE TITLE
Has this been updated to work with a Pi-4?

### ISSUE THREAD

**Issue by dadrepus** [snorre-k/musicbox#7]
Noticed that on the Music Box site that it has not been updated to work with the 4 yet. Has this?

**Comment by snorre-k** [comment]
The scripts should work with the Raspi4. Unfortunately I only have a PI Zero, but there it is tested with Raspbian Buster.

If you see any issues, please comment again.

**Comment by snorre-k** [comment]
I just checked again the installation on Raspian Buster. Unfortunately there are some bugs which I will try to resolve immediately.

**Comment by snorre-k** [comment]
Installation works now on Buster.

**Comment by snorre-k** [comment]
Tested on RPI4 with Raspian Buster and Hifiberry DAC+ Zero
