### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by nikitalpopov** [snorre-k/musicbox#8]
What's the fastest way to uninstall/remove all packages? Could you provide guide or shell script for that, please?

**Comment by snorre-k** [comment]
Hi,

Sorry for the late answer.
Unfortunately I do not have an uninstall script ... available right now.
The fastest way to get rid of the packages and changes is to write a new Raspberry PI OS (Raspbian) image to the  SD card.

CU
Snorre
